-- CreateTable
CREATE TABLE "saveOnFeed" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" TEXT NOT NULL,
    "fileId" TEXT NOT NULL,
    "happenedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "saveOnFeed_userId_fkey" FOREIGN KEY ("userId") REFERENCES "Users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "saveOnFeed_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "Files" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
